local addonName, ns = ...

local L = {}
ns.L = L

-- Fallback: return key if translation missing
setmetatable(L, { __index = function(_, k) return k end })

-- General
L["PI_ASSISTANT"]            = "Will Pay 4 PI"
L["ENABLED"]                 = "Enabled"
L["DISABLED"]                = "Disabled"
L["ENABLE"]                  = "Enable"
L["DISABLE"]                 = "Disable"
L["STATUS"]                  = "Status"
L["VERSION"]                 = "Version"
L["SAVE"]                    = "Save"
L["CANCEL"]                  = "Cancel"
L["RESET"]                   = "Reset"
L["DELETE"]                  = "Delete"
L["IMPORT"]                  = "Import"
L["EXPORT"]                  = "Export"
L["DUPLICATE"]               = "Duplicate"
L["ADD"]                     = "Add"
L["REMOVE"]                  = "Remove"
L["APPLY"]                   = "Apply"
L["CLOSE"]                   = "Close"
L["NONE"]                    = "None"
L["UNKNOWN"]                 = "Unknown"
L["YES"]                     = "Yes"
L["NO"]                      = "No"
L["OK"]                      = "OK"
L["TEST"]                    = "Test"
L["PREVIEW"]                 = "Preview"

-- Tabs
L["TAB_DASHBOARD"]           = "Dashboard"
L["TAB_PRIESTS"]             = "Priests"
L["TAB_BURST"]               = "Burst"
L["TAB_MESSAGES"]            = "Messages"
L["TAB_STATISTICS"]          = "Statistics"

-- Dashboard
L["DASH_CLASS"]              = "Class"
L["DASH_SPEC"]               = "Specialization"
L["DASH_HERO_TALENT"]        = "Hero Talent"
L["DASH_SELECTED_PRIEST"]    = "Selected Priest"
L["DASH_AVAILABLE_PRIESTS"]  = "Available Priests"
L["DASH_ADDON_STATUS"]       = "Addon Status"
L["DASH_LAST_REQUEST"]       = "Last Request"
L["DASH_LAST_PI"]            = "Last PI Received"
L["DASH_NEVER"]              = "Never"
L["DASH_JUST_NOW"]           = "Just now"
L["DASH_AGO"]                = "ago"

-- Priests
L["PRIEST_NAME"]             = "Name"
L["PRIEST_REALM"]            = "Realm"
L["PRIEST_SPEC"]             = "Spec"
L["PRIEST_ONLINE"]           = "Online"
L["PRIEST_ALIVE"]            = "Alive"
L["PRIEST_DISTANCE"]         = "Distance"
L["PRIEST_SELECTED"]         = "Selected"
L["PRIEST_PRIORITY"]         = "Priority"
L["PRIEST_SELECT"]           = "Select"
L["PRIEST_DESELECT"]         = "Deselect"
L["PRIEST_NO_PRIESTS"]       = "No Priests found in group"
L["PRIEST_OFFLINE"]          = "Offline"
L["PRIEST_DEAD"]             = "Dead"
L["PRIEST_RANGE_CLOSE"]      = "Close"
L["PRIEST_RANGE_FAR"]        = "Far"
L["PRIEST_RANGE_UNKNOWN"]    = "?"

-- Burst
L["BURST_SPELL_ID"]          = "Spell ID"
L["BURST_SPELL_NAME"]        = "Spell Name"
L["BURST_ACTIVE"]            = "Active"
L["BURST_COOLDOWN"]          = "Internal Cooldown"
L["BURST_WEIGHT"]            = "Weight"
L["BURST_PRIORITY"]          = "Priority"
L["BURST_EVENT_TYPE"]        = "Event Type"
L["BURST_ADD_SPELL"]         = "Add Spell"
L["BURST_REMOVE_SPELL"]      = "Remove Spell"
L["BURST_IMPORT_LIST"]       = "Import List"
L["BURST_EXPORT_LIST"]       = "Export List"
L["BURST_ENTER_SPELL_ID"]    = "Enter Spell ID..."
L["BURST_INVALID_ID"]        = "Invalid Spell ID"
L["BURST_SPELL_NOT_FOUND"]   = "Spell not found"
L["BURST_NO_SPELLS"]         = "No burst spells configured"
L["BURST_TEST"]              = "Test Burst"
L["BURST_SIMULATED"]         = "[SIMULATION] Burst detected"

-- Messages
L["MSG_TEMPLATE"]            = "Message Template"
L["MSG_CHANNEL"]             = "Channel"
L["MSG_COOLDOWN"]            = "Cooldown"
L["MSG_PREVIEW"]             = "Preview"
L["MSG_VARIABLES"]           = "Available Variables"
L["MSG_SEND_TEST"]           = "Send Test"
L["MSG_CHANNEL_WHISPER"]     = "Whisper"
L["MSG_CHANNEL_PARTY"]       = "Party"
L["MSG_CHANNEL_RAID"]        = "Raid"
L["MSG_CHANNEL_INSTANCE"]    = "Instance"
L["MSG_CHANNEL_SAY"]         = "Say"
L["MSG_CHANNEL_YELL"]        = "Yell"
L["MSG_CHANNEL_ADDON"]       = "Addon Channel"
L["MSG_NO_PRIEST"]           = "No Priest selected"
L["MSG_ON_COOLDOWN"]         = "Message on cooldown"
L["MSG_SENT"]                = "PI request sent to %s"
L["MSG_FAILED"]              = "Failed to send PI request: %s"

-- Statistics
L["STAT_BURSTS_DETECTED"]    = "Bursts Detected"
L["STAT_REQUESTS_SENT"]      = "Requests Sent"
L["STAT_PI_RECEIVED"]        = "PI Received"
L["STAT_PI_LOST"]            = "PI Lost"
L["STAT_SUCCESS_RATE"]       = "Success Rate"
L["STAT_TOP_PRIEST"]         = "Most Used Priest"
L["STAT_AVG_RESPONSE"]       = "Avg Response Time"
L["STAT_RESET_CONFIRM"]      = "Reset all statistics?"
L["STAT_HISTORY"]            = "History"
L["STAT_DATE"]               = "Date"
L["STAT_TIME"]               = "Time"
L["STAT_PRIEST"]             = "Priest"
L["STAT_MESSAGE"]            = "Message"
L["STAT_CHANNEL"]            = "Channel"
L["STAT_RESULT"]             = "Result"
L["STAT_SUCCESS"]            = "Success"
L["STAT_FAILED"]             = "Failed"
L["STAT_NO_HISTORY"]         = "No history yet"
L["STAT_SECONDS"]            = "%.1fs"

-- Alerts
L["ALERT_BURST_TITLE"]       = "BURST WINDOW"
L["ALERT_PI_REQUESTED"]      = "PI Requested → %s"
L["ALERT_PI_RECEIVED"]       = "Power Infusion Active!"
L["ALERT_NO_PRIEST"]         = "No Priest available for PI!"

-- Debug
L["DEBUG_TITLE"]             = "PI Assistant - Debug"
L["DEBUG_CLEAR"]             = "Clear"
L["DEBUG_COPY"]              = "Copy"
L["DEBUG_FILTER"]            = "Filter"
L["DEBUG_LEVEL"]             = "Log Level"
L["DEBUG_EVENTS"]            = "Events"
L["DEBUG_SPELLS"]            = "Spells"
L["DEBUG_PRIESTS"]           = "Priests"
L["DEBUG_MESSAGES"]          = "Messages"
L["DEBUG_COOLDOWNS"]         = "Cooldowns"
L["DEBUG_ERRORS"]            = "Errors"

-- Profiles
L["PROFILE_TITLE"]           = "Profiles"
L["PROFILE_CURRENT"]         = "Current Profile"
L["PROFILE_NEW"]             = "New Profile"
L["PROFILE_COPY"]            = "Copy"
L["PROFILE_DELETE"]          = "Delete"
L["PROFILE_EXPORT"]          = "Export Profile"
L["PROFILE_IMPORT"]          = "Import Profile"
L["PROFILE_PASTE_DATA"]      = "Paste profile data here..."
L["PROFILE_COPY_DATA"]       = "Copy the text below:"

-- Minimap menu
L["MENU_ENABLE"]             = "Enable PI Assistant"
L["MENU_TEST"]               = "Test Burst"
L["MENU_RESET_UI"]           = "Reset UI"
L["MENU_DEBUG"]              = "Debug Window"
L["MENU_OPTIONS"]            = "Options"

-- Errors
L["ERR_NO_GROUP"]            = "Not in a group"
L["ERR_PRIEST_DEAD"]         = "Selected Priest is dead"
L["ERR_PRIEST_OFFLINE"]      = "Selected Priest is offline"
L["ERR_PRIEST_NOT_IN_GROUP"] = "Selected Priest is not in group"
L["ERR_ON_COOLDOWN"]         = "Request on cooldown (%.0fs remaining)"
